import fs from 'node:fs/promises';
const html=await fs.readFile('index.html','utf8');
const files=['assets/js/core.js','assets/js/sources.js','assets/js/planner.js','assets/js/community.js','assets/js/app.js','assets/js/poi-sleep.js'];
const src=(await Promise.all(files.map(f=>fs.readFile(f,'utf8')))).join('\n');
for(const css of ['assets/css/app.css','assets/css/readability.css','assets/css/features.css','assets/css/poi-sleep.css'])if(!html.includes(css))throw Error(`CSS visual missing: ${css}`);
for(const js of files)if(!html.includes(js))throw Error(`JS missing: ${js}`);
for(const screen of ['home','create','route','savedRoutes','timeline','explore','destination','poiDetail','sleep','sleepDetail','favorites','spots','profile'])if(!html.includes(`data-screen="${screen}"`))throw Error(`Screen missing: ${screen}`);
for(const x of ['nominatim.openstreetmap.org','router.project-osrm.org','api.open-meteo.com','data/park4night-live.json'])if(!src.includes(x))throw Error(`Source missing: ${x}`);
if(/wikipedia\.org|wikimedia\.org|minube|reddit/i.test(src))throw Error('Forbidden old source found');
if(src.includes('Math.random')&&!(await fs.readFile('assets/js/core.js','utf8')).includes('Math.random'))throw Error('Random route selection found');
console.log('OK: visual CSS preserved, functional modules active, Park4Night preserved, obsolete sources removed.');
