import fs from 'node:fs/promises';
const html=await fs.readFile('index.html','utf8');
const files=['assets/js/app.js','assets/js/core.js','assets/js/state.js','assets/js/sources.js','assets/js/planner.js','assets/js/route-ui.js','assets/js/explore-ui.js','assets/js/camper-ui.js'];
const src=(await Promise.all(files.map(f=>fs.readFile(f,'utf8')))).join('\n');
const sources=await fs.readFile('assets/js/sources.js','utf8'),planner=await fs.readFile('assets/js/planner.js','utf8');
for(const id of ['home','create','route','timeline','explore','destination','poiDetail','sleep','sleepDetail','savedRoutes','favorites','spots','profile'])if(!html.includes(`data-screen="${id}"`))throw Error(`Missing screen ${id}`);
for(const id of ['calculate','generateRoutes','loadSleep','openPark4Night','addSpot'])if(!html.includes(`id="${id}"`))throw Error(`Missing action ${id}`);
if(!sources.includes('data/park4night-live.json'))throw Error('Missing Park4Night');
for(const x of ['nominatim.openstreetmap.org','router.project-osrm.org','api.open-meteo.com'])if(!sources.includes(x))throw Error(`Missing ${x}`);
if(!planner.includes('planThree')||planner.includes('Math.random'))throw Error('Planner invalid');
if(/wikipedia\.org|wikimedia\.org|minube|reddit/i.test(src))throw Error('Forbidden old source present');
console.log('Structure OK · Park4Night preserved · old sources removed · deterministic planner ready');
